version: '3'
http:
    address: '0.0.0.0:8080'
    middleware:
        - gzip
        - static
    static:
        dir: public
        forbid:
            - .php
            - .htaccess
    pool:
        num_workers: 16
        supervisor:
            max_worker_memory: 100
        allocate_timeout: 10m
        max_jobs: 100
server:
    command: 'php app.php'
    relay: pipes
kv:
    local:
        driver: memory
        config:
            interval: 60
    redis:
        driver: redis
        config:
         addrs:
            - redis:6379
metrics:
    address: '0.0.0.0:2112'
